apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-dev-tls
  namespace: app-dev
spec:
  secretName: app-dev-tls-secret          # cert+key will be stored here
  duration: 168h                          # 7 days
  renewBefore: 24h
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer       # the one you created
  dnsNames:
    - hello.dev.local