image:
  repository: gcr.io/google.com/cloudsdktool/google-cloud-cli
  tag: "slim"
  pullPolicy: IfNotPresent

namespace: app-${var.environment}

resources:
  requests:
    cpu: 100m
    memory: 128Mi