apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-b.fullname" . }}
  labels:
    app: {{ include "app-b.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-b.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-b.name" . }}
    spec:
      containers:
        - name: app-b
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}