name: Apply UAT UK 

on:
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      CI_SA: "github-ci@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      TF_WORKDIR: "./terraform"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: List Files
        run: ls -R

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Authenticate to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WI_PROVIDER }}
          service_account: ${{ env.CI_SA }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform -chdir=envs/uk-dev init

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform -chdir=envs/uk-uat apply -auto-approve -input=false -var="project_id=${{ secrets.GCP_PROJECT_ID }}" 